### ISSUE TITLE
Incorrect documentation in ElasticsearchReader

### ISSUE THREAD

**Issue by EivindEE** [comperiosearch/elasticsearch-eslib#4]
It seems that the pydoc at the start of the [ElasticsearchReader](https://github.com/comperiosearch/elasticsearch-eslib/blob/master/eslib/procs/ElasticsearchReader.py) is intended to be in [ElasticsearchWriter](https://github.com/comperiosearch/elasticsearch-eslib/blob/master/eslib/procs/ElasticsearchWriter.py) since it talks about writing to elasticsearch, and expecting elasticsearch documents.

The documentation should be changed to reflect what the class does.

**Comment by htb** [comment]
Fixed
